title: Researcher
url: "https://google.com"
baseurl: "/researcher"
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/google"
footer_text: "Portfolio for li"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
